# Generated by Django 4.2.4 on 2023-10-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('predicted_class', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='menu',
            field=models.ManyToManyField(blank=True, to='home.menus'),
        ),
    ]
