# Generated by Django 4.2.4 on 2023-10-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_predictedimage_tablebooking_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='menu',
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='selected_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
