# Generated by Django 4.2.4 on 2024-01-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_payment_table_booking_remove_payment_billing_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
