# Generated by Django 4.2.4 on 2024-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cateringmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringmenu',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='cateringmenu',
            name='category',
            field=models.CharField(choices=[('Veg Starter', 'Vegetarian Starter'), ('Non-Veg Starter', 'Non-Vegetarian Starter'), ('Veg-Main Course', 'Vegetarian Main Course'), ('Non-Veg Main Course', 'Non-Vegetarian Main Course'), ('Desert', 'Desert'), ('Drinks', 'Drinks')], max_length=100),
        ),
    ]
